Dauhaliavets/online-store-app

public/semastep.js
=> pull request semastep96

package-lock.json, src/components/header/Header.module.css, src/components/menu/Burger.jsx, src/components/menu/Burger.module.css, src/components/menu/Menu.jsx, src/components/menu/Menu.module.css
Пофиксил блюр для выезжающего меню
=> fix: fixed blur effect while menu opened

src/App.module.css, src/components/account/RegistrationForm.module.css, src/components/main/product_listing/result_and_sort/ResultAndSort.jsx, src/components/search/Form.module.css
Поправил ширину экрана, сделал 1920px. Изменил стили, чтобы инпут поиска не подсвечивался по краям.
Там ещё показывает изменения в отступах, тут я не при чём. У меня в vscode выставлены табы длиной три пробела, а у семёна видимо пробелы вместо табов
=> Refactoring (screen width, search input)

src/components/account/Account.jsx, src/components/account/LoginForm.jsx, src/components/account/LoginForm.module.css
=> feat: add login form component

package-lock.json, package.json, src/App.js, src/components/account/Account.jsx, src/components/account/Account.module.css, src/components/account/LoginForm.jsx, src/components/account/LoginForm.module.css, src/components/account/RegistrationForm.jsx, src/components/account/RegistrationForm.module.css, src/index.js
=> feat: add react-router-dom and base routes

src/components/main/product_listing/filterSideBar/FilterSideBar.jsx, src/components/main/product_listing/filterSideBar/FilterSideBar.module.css, src/components/main/product_listing/filterSideBar/filter/Filter.jsx, src/components/main/product_listing/filterSideBar/filter/Filter.module.css, src/js/filterProducts.js, src/redux-store/actions/productsActions.js, src/redux-store/reducers/productsReducer.js, src/redux-store/thunk/asyncActions.js
Фильтрация по цене готова
Добавил try catch в санку fetchProducts
Работаю над фильтрацией по брендам
=> Filter by price work

src/components/main/product_listing/filterSideBar/FilterSideBar.jsx, src/components/main/product_listing/filterSideBar/FilterSideBar.module.css, src/js/filterProducts.js, src/redux-store/reducers/productsReducer.js
Фильтр по брендам готов
Планирую сделать фильтр по категориям
=> Now can filter by brands

package-lock.json, src/components/main/product_listing/filterSideBar/FilterSideBar.jsx, src/components/main/product_listing/filterSideBar/FilterSideBar.module.css
Пофиксил селектор по параграфу из за которого съехала верстка
=> hot fix <p> css selector

src/App.js, src/components/main/product_listing/ProductListing.jsx, src/components/main/product_listing/products/Product/Product.jsx, src/components/main/product_listing/products/Product/Product.module.css, src/components/main/product_listing/products/Product/countChanger/CountChanger.jsx, src/components/main/product_listing/products/Product/countChanger/CountChanger.module.css, src/js/filterProducts.js, src/redux-store/actions/cartActions.js, src/redux-store/reducers/cartReducer.js
Теперь можно добавить в корзину, удалить, поменять количество товара со странички продуктов:)
=> Add / remove / change count in cart from products page

src/redux-store/reducers/cartReducer.js
=> refactor cartAddProduct reduser

src/components/main/product_listing/filterSideBar/FilterSideBar.jsx, src/components/main/product_listing/filterSideBar/FilterSideBar.module.css, src/components/main/product_listing/filterSideBar/categories/Categories.jsx, src/components/main/product_listing/filterSideBar/categories/Categories.module.css, src/js/filterProducts.js, src/redux-store/reducers/productsReducer.js
=> Filter by categories ready

src/App.js, src/components/account/Account.jsx, src/components/account/LoginForm/LoginForm.jsx, src/components/account/RegistrationForm/RegistrationForm.jsx, src/firebase/firebase.js, src/hooks/useAuth.js
Немного порефакторил компоненты
=> refactor: minor refactoring

src/components/main/product_listing/ProductListing.jsx, src/components/main/product_listing/products/Products.jsx, src/components/search/Input/Input.jsx, src/components/search/Input/Input.module.css, src/index.js, src/redux-store/actions/actionCreator.js, src/redux-store/actions/cartActions.js, src/redux-store/actions/productsActions.js, src/redux-store/reducer.js, src/redux-store/reducers/cartReducer.js, src/redux-store/reducers/productsReducer.js, src/redux-store/reducers/userReducer.js, src/redux-store/store.js
1. Добавил динамический поиск
2. Частично поправил экспорты на именованные
=> feat: add live search

src/components/account/ForgotPassword/ForgotPassword.jsx, src/components/account/ForgotPassword/ForgotPassword.module.css, src/components/account/LoginForm/LoginForm.jsx, src/components/account/LoginForm/LoginForm.module.css, src/components/account/RegistrationForm/RegistrationForm.jsx, src/components/account/Warnings/LoginWarning.jsx, src/index.js
Добавил функцию "забыл пароль"
=> feat: add "forgot password" feature

src/components/footer/Footer.jsx, src/components/footer/Footer.module.css
=> feat: add footer

package-lock.json, src/components/main/product_listing/products/Products.jsx, src/components/search/Input/Input.jsx, src/redux-store/reducers/productsReducer.js
Пофиксил очистку инпута при выборе продукта из строки поиска, поменял reduser продуктов.
Выбранный продукт теперь попадает в видимые продукты
При смене фильтров / категорий сбрасывается
=> fix input cleaning / chage reduser for chosen products

package-lock.json, src/App.js, src/components/cart/CartContainer/BuyForm/BuyForm.jsx, src/components/cart/CartContainer/BuyForm/ConfirmOrderContainer/ConfirmOrderContainer.jsx, src/components/cart/CartContainer/CartContainer.jsx, src/components/cart/CartContainer/ShoppingCart/Card/Card.jsx, src/components/cart/CartContainer/ShoppingCart/Card/SelectQuantity/SelectQuantity.jsx, src/components/cart/CartContainer/ShoppingCart/ShoppingCart.jsx, src/components/cart/CartContainer/SubTotal/SubTotal.jsx
Исправил импорты.
Пофиксил отображение картинок на карточке товара.
Добавил роут для страницы заказа.
=> D cart form

src/components/menu/Menu.jsx
сделал менюшку 7 категорий и all
=> 7 real categories in menu and all

src/components/menu/Menu.jsx
бургер отображает все категории (забыл убрать слайс)
=> in burger all categories

src/components/main/product_listing/filterSideBar/FilterSideBar.jsx
фильтр не сбрасывался после смены категорий и не отображались товары
=> reset filter after change category

src/components/main/product_listing/products/Products.jsx, src/components/menu/Burger.jsx, src/components/menu/Burger.module.css, src/components/search/Input/Input.module.css
Пофиксил ошибки key, сделал ключи строкой в продуктах и перенес на уровень выше в бургер меню.
Пофиксил цвета NavLink в бургере и в поиске
=> S fix reactkey err

src/components/main/product_listing/filterSideBar/FilterSideBar.jsx, src/components/search/Input/Input.jsx, src/components/search/Search.jsx, src/js/filterProducts.js, src/redux-store/actions/productsActions.js, src/redux-store/reducers/productsReducer.js
=> Search work good

src/components/main/product_listing/filterSideBar/FilterSideBar.jsx, src/components/main/product_listing/topBar/TopBar.jsx, src/components/search/Input/Input.jsx, src/components/search/Search.jsx, src/js/filterProducts.js, src/redux-store/actions/productsActions.js, src/redux-store/reducers/productsReducer.js
Текст у продуктового топ бара динамически меняется
=> Top bar text

src/App.js, src/assets/icons/pag-next.svg, src/assets/icons/pag-prev.svg, src/components/main/product_listing/ProductListing.jsx, src/components/main/product_listing/products/Product/pagination/Pagination.jsx, src/components/main/product_listing/products/Product/pagination/Pagination.module.css, src/components/main/product_listing/products/Products.jsx, src/components/main/product_listing/products/Products.module.css, src/components/main/product_listing/topBar/TopBar.jsx, src/components/main/product_listing/topBar/TopBar.module.css
1. Добавил пагинацию
2. Добавил выбор количества товаров, отображаемых на одной странице
=> V pagination

src/App.js, src/components/cart/CartContainer/BuyForm/BuyForm.jsx, src/components/cart/CartContainer/BuyForm/BuyForm.module.css, src/components/cart/CartContainer/BuyForm/ConfirmOrderContainer/OrderForm/Modal/Modal.jsx, src/components/cart/CartContainer/BuyForm/ConfirmOrderContainer/OrderForm/Modal/Modal.module.css, src/components/cart/CartContainer/BuyForm/ConfirmOrderContainer/OrderForm/OrderForm.jsx, src/components/cart/CartContainer/BuyForm/ConfirmOrderContainer/OrderForm/OrderForm.module.css, src/components/cart/CartContainer/CartContainer.jsx, src/components/cart/CartContainer/ShoppingCart/Card/Card.module.css, src/components/cart/CartContainer/ShoppingCart/ShoppingCart.jsx, src/components/cart/CartContainer/ShoppingCart/ShoppingCart.module.css, src/components/cart/CartContainer/SubTotal/SubTotal.jsx, src/components/cart/CartContainer/SubTotal/SubTotal.module.css, src/components/main/product_listing/filterSideBar/FilterSideBar.jsx
Форма подтверждения заказа.
Добавил модалку.
Пофиксил FilterSideBar, useEffect
=> D cart fix

src/components/main/cards/Cards.jsx, src/components/main/cards/card/Card.jsx, src/components/main/cards/card/Card.module.css
Сделал стартовую страничку работающей)
=> start page now work
